services:
  db:
    image: mariadb:10.6
    container_name: bookstack_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      retries: 5
      timeout: 5s

  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: http://localhost:6875
      DB_HOST: db
      DB_USER: bookstack
      DB_PASS: bookstackpass
      DB_DATABASE: bookstack
      APP_KEY: base64:X9gMq8TB2x0ahnj3/Zp5QtnzkUBXsDo+5DAvFBHLmXU=
    ports:
      - 6875:80
    volumes:
      - bookstack_data:/config

  botpress:
    image: botpress/server:latest
    container_name: botpress
    restart: unless-stopped
    environment:
      BP_PRODUCTION: false
      BP_HTTP_PORT: 3000
      EXTERNAL_URL: http://localhost:3000
      BOOKSTACK_BASEURL: http://bookstack:6875
      BOOKSTACK_TOKEN_ID: ${BOOKSTACK_TOKEN_ID}
      BOOKSTACK_TOKEN_SECRET: REPLACE_TOKEN_SECRET
    ports:
      - "3000:3000"
    volumes:
      - ./data:/botpress/data
    networks:
      - botnet

  bridge:
    build: ./bridge
    container_name: googlechat_bridge
    restart: unless-stopped
    environment:
      - BP_BASE=http://botpress:3000
      - BOT_ID=my-bot
    ports:
      - "8080:8080"
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

volumes:
  db_data:
  bookstack_data:
